-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text,
  rating INTEGER DEFAULT 1
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Google', 'https://google.com','search engine',5),
  ('Wikipedia', 'https://wikipedia.org','wiki',4),
  ('Youtube', 'https://youtube.com','videos',5),
  ('Thinkful', 'https://thinkful.com','coding bootcamp',5),
  ('GitHub', 'https://github.com','repo',5),
  ('Slack', 'https://slack.com','messenger',5),
  ('Yahoo', 'https://yahoo.com','outdated',5),
  ('FB', 'https://facebook.com','social media',5),
  ('Instagram', 'https://instagram.com','new social media',5),
  ('Amazon', 'https://amazon.com','shopping',5);